#!/usr/bin/env bash
# gen-clrenv.sh -- regenerate tests/qa/CLRENV.BAT from the hint list in source.
#
# CLRENV.BAT clears every measurement-affecting DOSKUTSU hint so a stale
# variable from an earlier cell cannot survive into a later one. Its header
# has claimed "generated from the engine+SDL hint list" since it was written,
# but no generator existed -- so it drifted, and by 2026-08-21 it was missing
# 97 of the 164 hints in the source, including BACKDROP_CACHE, SHOT_TICKS,
# PIN_NATIVE_MODE and every TAS_*.
#
# That is not cosmetic. Round R ran eight back-to-back cells and every one
# inherited SDL_HINT_DOSKUTSU_THRASH_CENTRE=0 from an earlier cell, so the
# control arm and the treatment arm were the same configuration and the round
# measured nothing. Cells only escape this when a reboot separates them.
#
#   bash tests/qa/gen-clrenv.sh            # rewrite CLRENV.BAT
#   bash tests/qa/gen-clrenv.sh --check    # exit 1 if it is stale (CI gate)
#
# UNION semantics: names already in CLRENV.BAT are never dropped, even if the
# grep no longer finds them. Some hints are assembled by string concatenation
# and would vanish from a source-derived list; removing a clear is a silent
# regression, so this only ever adds.
set -euo pipefail
cd "$(dirname "$0")/../.."
OUT=tests/qa/CLRENV.BAT

# From source: both spellings appear, and names ending in "_" are
# concatenation fragments rather than real variables.
from_src() {
  grep -rhoE 'SDL_HINT_DOSKUTSU_[A-Z0-9_]+|"DOSKUTSU_[A-Z0-9_]+"' \
    vendor/nxengine-evo/src vendor/SDL/src/video/dos 2>/dev/null \
    | tr -d '"' | sed 's/^SDL_HINT_//' | grep -vE '_$' | sort -u
}
# From the existing file, so nothing already cleared is ever lost.
from_bat() {
  [ -f "$OUT" ] || return 0
  tr -d '\r' < "$OUT" | sed -nE 's/^SET (SDL_HINT_)?(DOSKUTSU_[A-Z0-9_]+)=$/\2/p' | sort -u
}

NAMES=$( { from_src; from_bat; } | sort -u )

emit() {
  printf '@ECHO OFF\r\n'
  printf 'REM CLRENV.BAT -- wipe every measurement-affecting DOSKUTSU hint from the\r\n'
  printf 'REM environment so a stale SET from an earlier cell cannot survive into a\r\n'
  printf 'REM later one (env beats CFG by design). CALLed by every cell BAT except the\r\n'
  printf 'REM ENV PROBE cells (C1/G01), which deliberately run WITHOUT clears.\r\n'
  printf 'REM\r\n'
  printf 'REM GENERATED by tests/qa/gen-clrenv.sh -- do not hand-edit. Re-run it after\r\n'
  printf 'REM adding any DOSKUTSU_* hint, or the new lever will persist across cells.\r\n'
  printf 'REM Clearing is necessary but NOT sufficient: this file only reaches the card\r\n'
  printf 'REM on a populate, so a round must also assert its own control-arm levers are\r\n'
  printf 'REM absent rather than trusting that this ran.\r\n'
  while read -r n; do
    [ -n "$n" ] || continue
    printf 'SET %s=\r\n' "$n"
    printf 'SET SDL_HINT_%s=\r\n' "$n"
  done <<< "$NAMES"
}

if [ "${1:-}" = "--check" ]; then
  if emit | cmp -s - "$OUT"; then echo "CLRENV.BAT up to date"; exit 0; fi
  echo "CLRENV.BAT is STALE -- run: bash tests/qa/gen-clrenv.sh" >&2; exit 1
fi
emit > "$OUT.tmp" && mv "$OUT.tmp" "$OUT"
echo "wrote $OUT: $(grep -c '^SET ' "$OUT") clears, $(wc -l < "$OUT") lines"
