#!/usr/bin/env python3
"""
rename-sif.py — apply 8.3-filename renames to a sprites.sif file.

The 2FIS container format (reverse-engineered from
vendor/nxengine-evo/src/siflib/sifloader.cpp + sectStringArray.cpp):

  File header:
    [4]  magic        '2FIS'  -- the C constant SIF_MAGICK = ('S' << 24) +
                                 ('I' << 16) + ('F' << 8) + '2', read via
                                 fgetl() which is little-endian. Stored on
                                 disk as the bytes "2FIS".
    [1]  nsections    uint8

  Index table (nsections × 9 bytes):
    [1]  type         uint8   -- SIF_SECTION_* enum value
    [4]  foffset      uint32  -- absolute file offset to section data
    [4]  length       uint32  -- length of section data in bytes

  Section data lives at the offsets given by the index. Sections may appear
  in any order in the file; index ORDER drives lookup, not file order.

  The SIF_SECTION_SHEETS section (type==1) is a string-array section:
    [2]  nstrings     uint16
    For each string:
      [1]   len        uint8     -- 1..254 inline; 255 is escape for u16 length
      [2]   len_long   uint16    -- present only when len byte == 255
      [N]   bytes      ASCII (no NUL terminator)

What this script does:

  1. Parse the file's header + index table.
  2. Locate the SHEETS section.
  3. Decode the string array.
  4. Apply a hard-coded rename map (8.3-compliance) to each string.
  5. Re-encode the SHEETS section.
  6. Recompute file layout: shift section offsets in the index table to
     accommodate any size delta on SHEETS, keeping the on-disk section
     ORDER identical to the original.
  7. Write the new file.

Safety properties:

  * Round-trip mode (--check): reads, re-encodes WITHOUT applying renames,
    and asserts byte-identical output. Run before trusting the rewriter.
  * Idempotent: applying renames to an already-renamed sif is a no-op
    (the rename map's keys won't match anything; output is identical to
     input modulo the SHEETS section's regenerated bytes).
  * Refuses to write if the magic, nsections, or any index entry parses
    inconsistently.

Usage:
  scripts/rename-sif.py --check <sif>             # round-trip self-test
  scripts/rename-sif.py --in <sif> --out <sif>    # apply renames

License: MIT (this script). The data format is documented in NXEngine-evo
sources (GPLv3). This rewriter does not embed engine code; it only reads
and writes the file format.
"""

import argparse
import struct
import sys


SIF_MAGIC = b"2FIS"
SIF_SECTION_SHEETS = 1


# Rename map: keys are pre-rename strings as they currently appear in
# sprites.sif; values are the 8.3-compliant replacement. Mixed-case
# preserved to match Cave Story / NXEngine convention; DOS is
# case-insensitive but Linux dev hosts aren't.
#
# The map covers ONLY the sprite-sheet paths embedded in sprites.sif.
# Other long-name renames (StageMeta dir, root JSONs, etc.) are handled
# separately — by the source-side patch and the data-tree rename
# instructions in docs/ASSETS.md.
RENAME_MAP = {
    "ArmsImage.pbm": "ArmImg.pbm",
    "ItemImage.pbm": "ItmImg.pbm",
    "StageImage.pbm": "StgImg.pbm",
    "Npc/NpcBallos.pbm": "Npc/NpcBalls.pbm",
    "Npc/NpcIsland.pbm": "Npc/NpcIslnd.pbm",
    "Npc/NpcPriest.pbm": "Npc/NpcPrst.pbm",
    "Npc/NpcStream.pbm": "Npc/NpcStrm.pbm",
    "Stage/PrtAlmond.pbm": "Stage/PrtAlmnd.pbm",
}


def decode_pascal_string(buf, pos):
    """Read a Pascal string starting at buf[pos]; return (string, new_pos)."""
    n = buf[pos]
    pos += 1
    if n == 255:
        n = struct.unpack_from("<H", buf, pos)[0]
        pos += 2
    s = buf[pos:pos + n].decode("ascii")
    return s, pos + n


def encode_pascal_string(s):
    """Encode a string as a Pascal string (1-byte length, or 255 + u16)."""
    b = s.encode("ascii")
    n = len(b)
    if n < 255:
        return bytes([n]) + b
    return bytes([255]) + struct.pack("<H", n) + b


def decode_string_array(section_data):
    """Decode a SIF string-array section. Returns the list of strings."""
    nstrings = struct.unpack_from("<H", section_data, 0)[0]
    pos = 2
    out = []
    for _ in range(nstrings):
        s, pos = decode_pascal_string(section_data, pos)
        out.append(s)
    return out


def encode_string_array(strings):
    """Encode a list of strings as a SIF string-array section."""
    parts = [struct.pack("<H", len(strings))]
    for s in strings:
        parts.append(encode_pascal_string(s))
    return b"".join(parts)


def parse_header(blob):
    """Parse magic + index table. Returns (nsections, [(type, off, len)...])."""
    if blob[0:4] != SIF_MAGIC:
        sys.exit(f"rename-sif: bad magic: got {blob[0:4]!r}, expected {SIF_MAGIC!r}")
    nsections = blob[4]
    entries = []
    pos = 5
    for i in range(nsections):
        t = blob[pos]
        off, length = struct.unpack_from("<II", blob, pos + 1)
        entries.append((t, off, length))
        pos += 9
    return nsections, entries, pos  # pos = end-of-header (start of section data area)


def read_sections(blob, entries):
    """Read each section's data into a list parallel to entries."""
    return [blob[off:off + length] for (_, off, length) in entries]


def write_sif(nsections, entries, sections):
    """Serialize a sif file from header data + section bodies.

    Re-emits sections in the SAME on-disk order as the input file (sorted
    by current offset), recomputes new offsets to pack tightly, and updates
    the index table accordingly.
    """
    header_size = 5 + nsections * 9

    # Map each section index to its on-disk position by sorting on original
    # offset. We re-emit in that exact order so binary diff against an
    # unchanged round-trip stays minimal.
    disk_order = sorted(range(nsections), key=lambda i: entries[i][1])

    # Compute new offsets.
    new_offsets = [0] * nsections
    cursor = header_size
    for idx in disk_order:
        new_offsets[idx] = cursor
        cursor += len(sections[idx])
    total_size = cursor

    # Emit header.
    out = bytearray()
    out += SIF_MAGIC
    out += bytes([nsections])
    for i in range(nsections):
        t = entries[i][0]
        new_off = new_offsets[i]
        new_len = len(sections[i])
        out += bytes([t])
        out += struct.pack("<II", new_off, new_len)

    assert len(out) == header_size, "header size mismatch — index table miscomputed"

    # Emit section bodies in disk order.
    for idx in disk_order:
        # Pad/truncate? No — section bodies are emitted verbatim, no
        # alignment requirements per the loader.
        assert len(out) == new_offsets[idx], (
            f"emit order vs offset table mismatch at section {idx}"
        )
        out += sections[idx]

    assert len(out) == total_size
    return bytes(out)


def apply_rename(strings):
    """Apply the rename map. Returns (new_list, count_changed)."""
    out = []
    changed = 0
    for s in strings:
        if s in RENAME_MAP:
            out.append(RENAME_MAP[s])
            changed += 1
        else:
            out.append(s)
    return out, changed


def cmd_check(in_path):
    """Round-trip self-test: decode + re-encode without changes, compare bytes."""
    with open(in_path, "rb") as fp:
        original = fp.read()

    nsections, entries, _ = parse_header(original)
    sections = read_sections(original, entries)

    # Round-trip each string-array section we know about (just SHEETS for now).
    for i in range(nsections):
        if entries[i][0] == SIF_SECTION_SHEETS:
            strings = decode_string_array(sections[i])
            sections[i] = encode_string_array(strings)

    rebuilt = write_sif(nsections, entries, sections)

    if rebuilt == original:
        print(f"rename-sif --check: OK ({len(original)} bytes, byte-identical round-trip)")
        return 0

    # Diagnostic — find first divergence.
    for i in range(min(len(original), len(rebuilt))):
        if original[i] != rebuilt[i]:
            print(f"rename-sif --check: FAIL at byte {i}: "
                  f"original=0x{original[i]:02x} rebuilt=0x{rebuilt[i]:02x}",
                  file=sys.stderr)
            print(f"  original len={len(original)} rebuilt len={len(rebuilt)}",
                  file=sys.stderr)
            return 1
    if len(original) != len(rebuilt):
        print(f"rename-sif --check: FAIL length: "
              f"original={len(original)} rebuilt={len(rebuilt)}",
              file=sys.stderr)
        return 1
    return 1


def cmd_rename(in_path, out_path):
    """Apply the rename map to in_path; write to out_path."""
    with open(in_path, "rb") as fp:
        blob = fp.read()

    nsections, entries, _ = parse_header(blob)
    sections = read_sections(blob, entries)

    total_renamed = 0
    for i in range(nsections):
        if entries[i][0] == SIF_SECTION_SHEETS:
            strings = decode_string_array(sections[i])
            new_strings, n = apply_rename(strings)
            total_renamed += n
            sections[i] = encode_string_array(new_strings)
            for old, new in zip(strings, new_strings):
                if old != new:
                    print(f"  {old!r:30s} -> {new!r}")

    if total_renamed == 0:
        print("rename-sif: no strings matched the rename map "
              "(file may already be renamed, or RENAME_MAP is out of sync)",
              file=sys.stderr)

    rebuilt = write_sif(nsections, entries, sections)
    with open(out_path, "wb") as fp:
        fp.write(rebuilt)

    print(f"rename-sif: wrote {out_path} "
          f"({len(blob)} -> {len(rebuilt)} bytes, {total_renamed} strings renamed)")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--check", metavar="SIF", help="round-trip self-test on SIF")
    ap.add_argument("--in", dest="in_", metavar="SIF", help="input sif file")
    ap.add_argument("--out", metavar="SIF", help="output sif file")
    args = ap.parse_args()

    if args.check:
        sys.exit(cmd_check(args.check))
    if args.in_ and args.out:
        sys.exit(cmd_rename(args.in_, args.out))
    ap.print_help(sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
